<?php

function open_data_information_search_form_alter(&$form, &$form_state, $form_id) {
    switch($form_id){
        case 'dkan_sitewide_dataset_search_form' :
            $form['#submit'] = ['search_form_submit'];
       break;
    }
}

function search_form_submit($form, &$form_state) {
    switch($form['#action']){
       case '/data':
       case '/fr/data':
            $term = taxonomy_get_term_by_name('Open data', 'information_type');
       break;
       case '/information':
       case '/fr/information':
            $term = taxonomy_get_term_by_name('Open information', 'information_type');
       break;
    }
    $query = $form_state['input']['search'];
    if(!empty($term)){
        $id_term = array_keys($term);
        $id_term = $id_term[0];
        $name = str_replace(' ', '-', strtolower($term[$id_term]->name));
        drupal_goto('search/field_information_type/'.$name.'-' . $id_term , array('query' => array('query' => $query)));
    }
    else{
        drupal_goto('search' , array('query' => array('query' => $query)));
    }

}